######################################################################
# Automatically generated by qmake (3.0) ?? ???. 28 20:24:56 2017
######################################################################

TEMPLATE = app
TARGET = qt-test
INCLUDEPATH += .

# Input
HEADERS += MyGlWidget.h
SOURCES += qt-test.cpp

QT += widgets

